#!/usr/bin/env ruby

require "sqlite3"
require "yaml"

class PathList
  DEFAULT_DATABASE = File.join(File.expand_path(File.dirname(__FILE__)), 'dlpaths.db')
  DEFAULT_YAML = 'dirlist.yml'

  def self.run(args, current_path)
    return usage unless [1, 2].include?(args.size)
    command, shortcut = args
    case command
    when 'add'
      if shortcut.nil?
        self.new.add(File.basename(current_path), current_path)
      else
        self.new.add(shortcut, current_path)
      end
    when 'remove'
      self.new.remove(shortcut)
    when 'update'
      self.new.update(shortcut, current_path)
    when 'list'
      self.new.list
    when 'find'
      self.new.find(shortcut)
    when 'export'
      self.new.export(current_path, shortcut || DEFAULT_YAML)
    when 'import'
      self.new.import(current_path, shortcut || DEFAULT_YAML)
    when 'wipe'
      self.new.wipe
    else
      usage
    end
  end

  def self.usage
    puts "usage: dirbase <command> [<alias>]"
    puts
    puts "Available commands are:"
    puts "  add     Store a new directory alias"
    puts "  remove  Remove an existing alias"
    puts "  update  Alter path associated with alias"
    puts "  list    List all known alias->path pairs"
    puts "  find    Find directory corresponding to given alias"
    puts "  export  Output yaml file containing all paths"
    puts "  import  Import paths from a given yaml file"
    puts "  wipe    Remove all stored alias->path pairs"
  end

  def initialize(database_name = DEFAULT_DATABASE)
    @db = SQLite3::Database.new(database_name)
    create_schema
  end

  def add(shortcut, path)
    begin
      @db.execute("INSERT INTO paths VALUES (?, ?)", [shortcut, path])
      puts "added #{shortcut.inspect} => #{path.inspect}"
    rescue SQLite3::ConstraintException => e
      old_shortcut, old_path = find(shortcut)
      puts "alias already exists: #{old_shortcut.inspect} => #{old_path.inspect}"
      if path != old_path
        print "update to new path #{path.inspect}? (y/n) "
        response = $stdin.gets.chomp.strip
        if ['y', 'yes'].include?(response.downcase)
          update(shortcut, path)
        end
      end
    end
  end

  def update(shortcut, path)
    @db.execute("UPDATE paths SET path = ? WHERE alias = ?", [path, shortcut])
    puts "updated #{shortcut.inspect} => #{path.inspect}"
  end

  def remove(shortcut)
    @db.execute("DELETE FROM paths WHERE alias = ?", shortcut)
    puts "removed #{shortcut.inspect}"
  end

  def wipe
    @db.execute("DELETE FROM paths")
    puts "removed all stored paths"
  end

  def find(shortcut)
    rows = @db.execute("SELECT alias, path FROM paths WHERE alias = ?", shortcut)
    if rows.empty?
      puts "unknown path alias: #{shortcut.inspect}"
      exit(false)
    else
      puts rows[0][1]
      exit(true)
    end
  end

  def list
    rows = @db.execute("SELECT alias, path FROM paths ORDER BY alias")
    results = rows.map { |a, p| [a, p] }
    padding = results.empty? ? 0 : results.max { |x,y| x[0].size <=> y[0].size }[0].size
    lines = results.map { |a, p| "%-#{padding}s => %s" % [a, p] }
    puts lines.join("\n")
  end

  def export(current_path, filename)
    rows = @db.execute("SELECT alias, path FROM paths ORDER BY alias")
    results = rows.map { |a, p| [a, p] }
    padding = results.empty? ? 0 : results.max { |x,y| x[0].size <=> y[0].size }[0].size
    lines = results.map { |a, p| "%-#{padding}s: %s\n" % [a, p] }
    output_file = File.join(current_path, filename)
    File.open(output_file, "w") do |file|
      lines.each { |line| file << line}
    end
  end

  def import(current_path, filename)
    input_file = File.join(current_path, filename)
    if !File.exist?(input_file)
      puts "import file not found: #{input_file}"
    else
      paths = YAML::load_file(input_file)
      paths.each_pair { |a,p| add_or_update(a, p) }
    end
  end

  private

  def create_schema
    results = @db.execute <<-SQL
      CREATE TABLE IF NOT EXISTS paths (
        alias TEXT PRIMARY KEY,
        path TEXT
      );
    SQL
  end

  def add_or_update(shortcut, path)
    begin
      @db.execute("INSERT INTO paths VALUES (?, ?)", [shortcut, path])
    rescue SQLite3::ConstraintException => e
      @db.execute("UPDATE paths SET path = ? WHERE alias = ?", [path, shortcut]) rescue nil
    end
  end

end


if __FILE__ == $0
  PathList.run ARGV, Dir.pwd
end
